name: Keep Render App Awake

# Run the workflow on a schedule
on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: |
          # Try to hit /health (or root) and fail if non-200
          curl --fail https://eliud-backend-server.onrender.com/health \
            && echo "✅ Ping successful" \
            || echo "❌ Ping failed"
