name: Keep Render App Awake

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  workflow_dispatch:         # allow manual runs from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: |
          curl --fail https://eliud-backend-server.onrender.com/health \
            && echo "✅ Ping successful" \
            || echo "❌ Ping failed"
